import Bot from './struct/Client.js';
import config from '../config.json';
const client = new Bot();
console.log('starting..');
client.login(config.token);
client.loadCommands();
client.loadEvents();
client.loadDatabase();
client.loadGuilds();
console.log('hi!');
